services:
#    app_foundations_communications.example:
#        class: AppFoundations\CommunicationsBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

#    app_foundations_communications.dummy_email_provider:
#        class: 'AppFoundations\CommunicationsBundle\EmailServiceProvider\Dummy\DummyEmailProvider'
#
#    app_foundations_communications.send_grid_provider:
#        class: 'AppFoundations\CommunicationsBundle\EmailServiceProvider\SendGrid\SendGridProvider'
#        arguments:
#            - '%app_foundations_communications.email.sendgrid_key%'

    app_foundations_communications.basic_email_dispatcher:
        class: 'AppFoundations\CommunicationsBundle\Service\BasicHMailDispatcher'
        arguments: ['%app_foundations_communications.email%']

    app_foundations_communications.hermes_email_service:
        class: 'AppFoundations\CommunicationsBundle\Service\HermesEmailService'
        arguments: ['@app_foundations_communications.basic_email_dispatcher']
        
    app_foundations_communications.hermes_sms_service:
        class: 'AppFoundations\CommunicationsBundle\Service\HermesSmsService'
        arguments:
        - '%app_foundations_communications.sms%'
        - '@doctrine'
        - '@logger'